// Code generated by gotsrpc https://github.com/foomo/gotsrpc/v2  - DO NOT EDIT.

package server

import (
	io "io"
	http "net/http"
	time "time"

	gotsrpc "github.com/foomo/gotsrpc/v2"
	github_com_foomo_webgrapple_pkg_vo "github.com/foomo/webgrapple/pkg/vo"
)

const (
	ServiceGoTSRPCProxyRemove = "Remove"
	ServiceGoTSRPCProxyUpsert = "Upsert"
)

type ServiceGoTSRPCProxy struct {
	EndPoint string
	service  *Service
}

func NewDefaultServiceGoTSRPCProxy(service *Service) *ServiceGoTSRPCProxy {
	return NewServiceGoTSRPCProxy(service, "/___webgrapple-service")
}

func NewServiceGoTSRPCProxy(service *Service, endpoint string) *ServiceGoTSRPCProxy {
	return &ServiceGoTSRPCProxy{
		EndPoint: endpoint,
		service:  service,
	}
}

// ServeHTTP exposes your service
func (p *ServiceGoTSRPCProxy) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	if r.Method == http.MethodOptions {
		return
	} else if r.Method != http.MethodPost {
		gotsrpc.ErrorMethodNotAllowed(w)
		return
	}
	defer io.Copy(io.Discard, r.Body) // Drain Request Body

	funcName := gotsrpc.GetCalledFunc(r, p.EndPoint)
	callStats, _ := gotsrpc.GetStatsForRequest(r)
	callStats.Func = funcName
	callStats.Package = "github.com/foomo/webgrapple/pkg/server"
	callStats.Service = "Service"
	switch funcName {
	case ServiceGoTSRPCProxyRemove:
		var (
			args []interface{}
			rets []interface{}
		)
		var (
			arg_serviceIDs []github_com_foomo_webgrapple_pkg_vo.ServiceID
		)
		args = []interface{}{&arg_serviceIDs}
		if err := gotsrpc.LoadArgs(&args, callStats, r); err != nil {
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		executionStart := time.Now()
		removeErr := p.service.Remove(arg_serviceIDs)
		callStats.Execution = time.Since(executionStart)
		rets = []interface{}{removeErr}
		if err := gotsrpc.Reply(rets, callStats, r, w); err != nil {
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	case ServiceGoTSRPCProxyUpsert:
		var (
			args []interface{}
			rets []interface{}
		)
		var (
			arg_services []*github_com_foomo_webgrapple_pkg_vo.Service
		)
		args = []interface{}{&arg_services}
		if err := gotsrpc.LoadArgs(&args, callStats, r); err != nil {
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		executionStart := time.Now()
		upsertErr := p.service.Upsert(arg_services)
		callStats.Execution = time.Since(executionStart)
		rets = []interface{}{upsertErr}
		if err := gotsrpc.Reply(rets, callStats, r, w); err != nil {
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	default:
		gotsrpc.ClearStats(r)
		gotsrpc.ErrorFuncNotFound(w)
	}
}
